srpv_admin:
    resource: "@ComunesSecurityBundle/Resources/config/routing/admin.yml"
    prefix:   /admin

_login:
    pattern:  /login/
    defaults: { _controller: ComunesSecurityBundle:Security:login }     
_login_check:
    pattern:  /login_check
_logout:
    pattern:  /logout
    defaults: { _controller: ComunesSecurityBundle:Security:logout}        