services:
    security.access.blacklist_voter:
        class:      Comunes\SecurityBundle\Authorization\ControlAccesByRole
        public:     false
        tags:
            - { name: security.voter }
        
##########  PROVEEDOR DE USUARIOS PARA  BANAVIH  ###########     
    users_provider:
        class:  Comunes\SecurityBundle\Provider\UsuarioBanavihProvider
        arguments:  
            entityManager: "@doctrine.orm.entity_manager"
