srpv_protocolizacion_protocolizacion_desarrollo:
    resource: "@SrpvProtocolizacionBundle/Resources/config/routing/desarrollo.yml"
    prefix:   /protocolizacion/desarrollo

srpv_protocolizacion_homepage:
    path:     /hello/{name}
    defaults: { _controller: SrpvProtocolizacionBundle:Default:index }