srpv_protocolizacion_vivienda:
    resource: "@SrpvProtocolizacionBundle/Resources/config/routing/vivienda.yml"
    prefix:   /protocolizacion/vivienda

srpv_protocolizacion_unidad:
    resource: "@SrpvProtocolizacionBundle/Resources/config/routing/unidadhabitacional.yml"
    prefix:   /protocolizacion/unidad

srpv_protocolizacion_desarrollo:
    resource: "@SrpvProtocolizacionBundle/Resources/config/routing/desarrollo.yml"
    prefix:   /protocolizacion/desarrollo

srpv_protocolizacion_beneficiario:
    resource: "@SrpvProtocolizacionBundle/Resources/config/routing/beneficiario.yml"
    prefix:   /protocolizacion/beneficiario

srpv_protocolizacion_homepage:
    path:     /hello/{name}
    defaults: { _controller: SrpvProtocolizacionBundle:Default:index }

updateDesarrollo:
    path:     /updateDesarollo/{id}
    defaults: { _controller: SrpvProtocolizacionBundle:Default:updateDesarrollo }

updateUnidad:
    path:     /updateUnidad/{id}
    defaults: { _controller: SrpvProtocolizacionBundle:Default:updateUnidad }

updateUnidadVivienda:
    path:     /updateUnidadVivienda/{id}
    defaults: { _controller: SrpvProtocolizacionBundle:Default:updateUnidadVivienda }

updateMunicipio:
    path:     /updateMunicipio/{id}
    defaults: { _controller: SrpvProtocolizacionBundle:Default:updateMunicipio }

updateParroquia:
    path:     /updateParroquia/{id}
    defaults: { _controller: SrpvProtocolizacionBundle:Default:updateParroquia }

actualizarMunicipio:
    path:     /actualizarMunicipio/{id}
    defaults: { _controller: SrpvProtocolizacionBundle:Default:actualizarMunicipio }

actualizarParroquia:
    path:     /actualizarParroquia/{id}
    defaults: { _controller: SrpvProtocolizacionBundle:Default:actualizarParroquia }

srpv_protocolizacion_carga_beneficiario:
    resource: "@SrpvProtocolizacionBundle/Resources/config/routing/cargaArchivoBeneficiario.yml"
    prefix:   /protocolizacion/carga_archivo

srpv_protocolizacion_adjudicados:
    resource: "@SrpvProtocolizacionBundle/Resources/config/routing/adjudicados.yml"
    prefix:   /protocolizacion/adjudicados