condicionessubsidio:
    path:     /
    defaults: { _controller: "SrpvAdminBundle:CondicionesSubsidio:index" }

condicionessubsidio_show:
    path:     /{id}/show
    defaults: { _controller: "SrpvAdminBundle:CondicionesSubsidio:show" }

condicionessubsidio_new:
    path:     /new
    defaults: { _controller: "SrpvAdminBundle:CondicionesSubsidio:new" }

condicionessubsidio_create:
    path:     /create
    defaults: { _controller: "SrpvAdminBundle:CondicionesSubsidio:create" }
    requirements: { _method: post }

condicionessubsidio_edit:
    path:     /{id}/edit
    defaults: { _controller: "SrpvAdminBundle:CondicionesSubsidio:edit" }

condicionessubsidio_update:
    path:     /{id}/update
    defaults: { _controller: "SrpvAdminBundle:CondicionesSubsidio:update" }
    requirements: { _method: post|put }

condicionessubsidio_delete:
    path:     /{id}/delete
    defaults: { _controller: "SrpvAdminBundle:CondicionesSubsidio:delete" }
    requirements: { _method: post|delete }
