imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig', 'php']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        gc_probability: 0
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    #Agregado para que funcione Bootstrap
    form:
        resources:
            - BraincraftedBootstrapBundle:Form:bootstrap.html.twig

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        less: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

        #Agregado para que funcione Bootstrap
        less:
            node: /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules]
            apply_to: "\.less$"
    assets:
        sisprov_css:
            inputs:
                - %kernel.root_dir%/Resources/less/sisprov.less
            filters:
                - less
                - cssrewrite
            output: css/sisprov.css
            

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: sisprov
        connections:                         
            sisprov:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8

            tablas_comunes:
                driver:   %database_driver2%
                host:     %database_host2%
                port:     %database_port2%
                dbname:   %database_name2%
                user:     %database_user2%
                password: %database_password2%
                charset:  UTF8
                
            organismos_publicos:
                driver:   %database_driver3%
                host:     %database_host3%
                port:     %database_port3%
                dbname:   %database_name3%
                user:     %database_user3%
                password: %database_password3%
                charset:  UTF8    

        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: sisprov 
        entity_managers:
            sisprov:
                connection: sisprov
                auto_mapping: false
                mappings: 
                    SrpvProtocolizacionBundle: ~
                    ComunesTablasBundle: ~
                    ComunesSecurityBundle: ~
                    ComunesOrganismosPublicosBundle: ~
                                        
            tablas_comunes:
                connection: tablas_comunes
                auto_mapping: false
                mappings: 
                    ComunesTablasBundle: ~
                    ComunesSecurityBundle: ~
                    ComunesOrganismosPublicosBundle: ~
            
            organismos_publicos:
                connection: organismos_publicos
                auto_mapping: false
                mappings: 
                    ComunesOrganismosPublicosBundle: ~   

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Bootstrap Configuration
braincrafted_bootstrap:
    output_dir:
    assets_dir: %kernel.root_dir%/../vendor/twbs/bootstrap
    jquery_path: %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.10.2.js
    
    # "less", "lessphp", "sass" or "none"
    less_filter: less 
    
    auto_configure:
        assetic: true
        twig: true
#        knp_menu: true
#        knp_paginator: true
    customize:
        variables_file: %kernel.root_dir%/Resources/less/variables.less  
        bootstrap_output: %kernel.root_dir%/Resources/less/sisprov.less
        bootstrap_template: BraincraftedBootstrapBundle:Bootstrap:bootstrap.less.twig