imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig', 'php']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        less: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: sisprov
        connections:                         
            sisprov:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8

            tablas_comunes:
                driver:   %database_driver2%
                host:     %database_host2%
                port:     %database_port2%
                dbname:   %database_name2%
                user:     %database_user2%
                password: %database_password2%
                charset:  UTF8
                
            organismos_publicos:
                driver:   %database_driver3%
                host:     %database_host3%
                port:     %database_port3%
                dbname:   %database_name3%
                user:     %database_user3%
                password: %database_password3%
                charset:  UTF8
#    dbal:
#        driver:   "%database_driver%"
#        host:     "%database_host%"
#        port:     "%database_port%"
#        dbname:   "%database_name%"
#        user:     "%database_user%"
#        password: "%database_password%"
#        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
       auto_generate_proxy_classes: "%kernel.debug%"
       auto_mapping: true
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: sisprov 
        entity_managers:
            sisprov:
                connection: sisprov
                auto_mapping: false
                mappings: 
                    SrpvProtocolizacionBundle: ~
                    ComunesTablasBundle: ~
                    ComunesSecurityBundle: ~
                    ComunesOrganismosPublicosBundle: ~
                                        
            tablas_comunes:
                connection: tablas_comunes
                auto_mapping: false
                mappings: 
                    ComunesTablasBundle: ~
                    ComunesSecurityBundle: ~
                    ComunesOrganismosPublicosBundle: ~
            
            organismos_publicos:
                connection: organismos_publicos
                auto_mapping: false
                mappings: 
                    ComunesOrganismosPublicosBundle: ~  

# Swiftmailer Configuration
swiftmailer:
    transport:  smtp
    encryption: ssl
    auth_mode:  login
    host:       smtp.gmail.com 
    username:   jponce@bmt.com.ve
    password:   18709948
    spool:     { type: memory }

#knp_paginator:
#    page_range: 5  # número de páginas a mostrar
#    default_options:
#       page_name: page # nombre del parámetro de paginación
#       sort_field_name: sort  # nombre del parámetro para ordenar los registros
#       sort_direction_name: direction # nombre del parámetro para ordenar la dirección de los registros
#       distinct: true # incluir resultados diferentes, útil en consultas con GROUP BY
#    template:
#        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig # plantilla utilizada en la paginación
#        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # plantilla utilizada en la paginación para ordenar los resultados