security:
    encoders:
#        #(ciudadanos) Ciudadanos Registrados en BANAVEL
#        Banavel\SecurityCddnoBundle\Entity\SolicitudUsuarioNat: 
#            algorithm:   md5
#            iterations: 1
#            encode_as_base64: false
#            
#        #(opf) Operadores Financieros y BANAVIH en Tablas Comunes    
#        Comunes\SecurityBundle\Entity\Usuario: 
#            algorithm:   md5
#            iterations: 1
#            encode_as_base64: false
#            
        #(admin) Administrador del Sistema
        Symfony\Component\Security\Core\User\User: 
            algorithm:   md5
            iterations: 1
            encode_as_base64: false                
            
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]    
        
    providers:        
#        cddno: 
#            entity: { class: Banavel\SecurityCddnoBundle\Entity\SolicitudUsuarioNat, property: usuario }
#        opf:
#            #Nombre del Servicio que llama al Comunes\SecurityBundle\Entity\UsuarioOpfProvider
#            id: opf_provider        
#            
#        bnvh:
#            #Nombre del Servicio que llama al Comunes\SecurityBundle\Entity\UsuarioBanavihProvider
#            id: bnvh_provider             
            
        administrador:
            memory:
                users:
                    admin: { password: 25e4ee4e9229397b6b17776bfceaf8e7, roles: [ 'ROLE_ADMIN' ] }         

    firewalls:   
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        ######  CIUDADANO  #######                
#        login_ciudadano:
#            pattern:  ^/cddno/login/$
#            anonymous: ~
#
#        ciudadano_secured_area:
#            provider: cddno
#            pattern:    ^/cddno
#            form_login:
#                check_path: /cddno/login_check
#                login_path: /cddno/login/
#                username_parameter: _usinsajo
#                password_parameter: _psinsajo
#            logout:
#                path:   /cddno/logout
#                target: /

        ######  ADMINISTRADOR  #######   
        login_admin:
            pattern:  ^/admin/login/$
            anonymous: ~
            
        admin_secured_area:
            provider: administrador
            pattern:    ^/admin
            form_login:
                check_path: /admin/login_check
                login_path: /admin/login/
                username_parameter: _usinsajo
                password_parameter: _psinsajo                
            logout:
                path:   /admin/logout
                target: /

#        ######  OPF  #######   
#        login_opf:
#            pattern:  ^/opf/login/$
#            anonymous: ~
#            
#        opf_secured_area:
#            provider: opf
#            pattern:    ^/opf
#            form_login:
#                check_path: /opf/login_check
#                login_path: /opf/login/
#                username_parameter: _usinsajo
#                password_parameter: _psinsajo                
#            logout:
#                path:   /opf/logout
#                target: /
#        ######  BANAVIH  #######   
#        bnvh_opf:
#            pattern:  ^/bnvh/login/$
#            anonymous: ~
#            
#        bnvh_secured_area:
#            provider: bnvh
#            pattern:    ^/bnvh
#            form_login:
#                check_path: /bnvh/login_check
#                login_path: /bnvh/login/
#                username_parameter: _usinsajo
#                password_parameter: _psinsajo                
#            logout:
#                path:   /bnvh/logout
#                target: /
              
    access_control:
#        - { path: ^/cddno/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/opf/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/bnvh/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
#        - { path: ^/cddno, roles: ROLE_CDDNO }  
        
    access_decision_manager:
        # strategy can be: affirmative, unanimous or consensus
        strategy: unanimous
#        allow_if_all_abstain: true        
