Comunes\TablasBundle\Entity\GeoPais:
    type: entity
    table: GEO_PAIS
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: 'número de identificación de la tabla'
            id: true
            column: id
            generator:
                strategy: SEQUENCE
    fields:
        nombre:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: 'nombre del país'
            column: NOMBRE
    lifecycleCallbacks: {  }
