adjudicados:
    path:     /
    defaults: { _controller: "SrpvProtocolizacionBundle:Adjudicados:index" }

asignacionAdjudicados:
    path:     /asignacion
    defaults: { _controller: "SrpvProtocolizacionBundle:Adjudicados:asignacionAdjudicados" }

detalleasignacionAdjudicados:
    path:     /asignacionDetalle/{id}
    defaults: { _controller: "SrpvProtocolizacionBundle:Adjudicados:detalleasignacionAdjudicados" }

asignacionIndividual:
    path:     /individual
    defaults: { _controller: "SrpvProtocolizacionBundle:Adjudicados:individual" }

asignacionMasival:
    path:     /masiva
    defaults: { _controller: "SrpvProtocolizacionBundle:Adjudicados:masiva" }

asignacionMasivaAdjudicados:
    path:     /asignacionMasiva
    defaults: { _controller: "SrpvProtocolizacionBundle:Adjudicados:asignacionMasivaAdjudicados" }

formToRedirectIndividual:
    path:     /formToRedirectIndividual
    defaults: { _controller: "SrpvProtocolizacionBundle:Adjudicados:formToRedirectIndividual" }

formToRedirectMasivo:
    path:     /formToRedirectMasivo
    defaults: { _controller: "SrpvProtocolizacionBundle:Adjudicados:formToRedirectMasivo" }

reasignacionMasivaAdjudicados:
    path:     /reasignacionMasiva
    defaults: { _controller: "SrpvProtocolizacionBundle:Adjudicados:reasignacionMasivaAdjudicados" }
