protocolizacion_desarrollo:
    path:     /
    defaults: { _controller: "SrpvProtocolizacionBundle:Desarrollo:index" }

protocolizacion_desarrollo_show:
    path:     /{id}/show
    defaults: { _controller: "SrpvProtocolizacionBundle:Desarrollo:show" }

protocolizacion_desarrollo_new:
    path:     /new
    defaults: { _controller: "SrpvProtocolizacionBundle:Desarrollo:new" }

protocolizacion_desarrollo_create:
    path:     /create
    defaults: { _controller: "SrpvProtocolizacionBundle:Desarrollo:create" }
    requirements: { _method: post }

protocolizacion_desarrollo_edit:
    path:     /{id}/edit
    defaults: { _controller: "SrpvProtocolizacionBundle:Desarrollo:edit" }

protocolizacion_desarrollo_update:
    path:     /{id}/update
    defaults: { _controller: "SrpvProtocolizacionBundle:Desarrollo:update" }
    requirements: { _method: post|put }

protocolizacion_desarrollo_delete:
    path:     /{id}/delete
    defaults: { _controller: "SrpvProtocolizacionBundle:Desarrollo:delete" }
    requirements: { _method: post|delete }
