unidad:
    path:     /
    defaults: { _controller: "SrpvProtocolizacionBundle:UnidadHabitacional:index" }

unidad_show:
    path:     /{id}/show
    defaults: { _controller: "SrpvProtocolizacionBundle:UnidadHabitacional:show" }

unidad_new:
    path:     /new
    defaults: { _controller: "SrpvProtocolizacionBundle:UnidadHabitacional:new" }

unidad_create:
    path:     /create
    defaults: { _controller: "SrpvProtocolizacionBundle:UnidadHabitacional:create" }
    requirements: { _method: post }

unidad_edit:
    path:     /{id}/edit
    defaults: { _controller: "SrpvProtocolizacionBundle:UnidadHabitacional:edit" }

unidad_update:
    path:     /{id}/update
    defaults: { _controller: "SrpvProtocolizacionBundle:UnidadHabitacional:update" }
    requirements: { _method: post|put }

unidad_delete:
    path:     /{id}/delete
    defaults: { _controller: "SrpvProtocolizacionBundle:UnidadHabitacional:delete" }
    requirements: { _method: post|delete }
