Comunes\SecurityBundle\Entity\GenPregConfirmacion:
    type: entity
    table: GEN_PREG_CONFIRMACION
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: 'número de identificación de la tabla'
            id: true
            column: id
            generator:
                strategy: SEQUENCE
    fields:
        nombre:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: 'nombre de la pregunta'
            column: NOMBRE
    lifecycleCallbacks: {  }
