# RUTAS PARA LOGIN /LOGOUT E INDEX  DEL ADMINISTRADOR DEL SISTEMA
sicc_admin_homepage:
    pattern:  /
    defaults: { _controller: ComunesSecurityBundle:Security:indexAdmin }  
admin_login:
    pattern:  /login/
    defaults: { _controller: ComunesSecurityBundle:Security:login }     
admin_login_check:
    pattern:  /login_check
admin_logout:
    pattern:  /logout
    defaults: { _controller: ComunesSecurityBundle:Security:logoutAdmin}     