<?php

namespace Proxies\__CG__\Srpv\ProtocolizacionBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class RegistroDocumento extends \Srpv\ProtocolizacionBundle\Entity\RegistroDocumento implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\RegistroDocumento' . "\0" . 'id', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\RegistroDocumento' . "\0" . 'ano', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\RegistroDocumento' . "\0" . 'fechaCreacion', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\RegistroDocumento' . "\0" . 'fechaModificacion', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\RegistroDocumento' . "\0" . 'fechaRegistro', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\RegistroDocumento' . "\0" . 'nroMatricula', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\RegistroDocumento' . "\0" . 'nroProtocolo', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\RegistroDocumento' . "\0" . 'nroRegistro', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\RegistroDocumento' . "\0" . 'tomo', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\RegistroDocumento' . "\0" . 'analisisCredito', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\RegistroDocumento' . "\0" . 'fuenteDatosEntrada', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\RegistroDocumento' . "\0" . 'usuario', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\RegistroDocumento' . "\0" . 'registroPublico');
        }

        return array('__isInitialized__', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\RegistroDocumento' . "\0" . 'id', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\RegistroDocumento' . "\0" . 'ano', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\RegistroDocumento' . "\0" . 'fechaCreacion', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\RegistroDocumento' . "\0" . 'fechaModificacion', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\RegistroDocumento' . "\0" . 'fechaRegistro', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\RegistroDocumento' . "\0" . 'nroMatricula', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\RegistroDocumento' . "\0" . 'nroProtocolo', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\RegistroDocumento' . "\0" . 'nroRegistro', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\RegistroDocumento' . "\0" . 'tomo', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\RegistroDocumento' . "\0" . 'analisisCredito', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\RegistroDocumento' . "\0" . 'fuenteDatosEntrada', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\RegistroDocumento' . "\0" . 'usuario', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\RegistroDocumento' . "\0" . 'registroPublico');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (RegistroDocumento $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAno($ano)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAno', array($ano));

        return parent::setAno($ano);
    }

    /**
     * {@inheritDoc}
     */
    public function getAno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAno', array());

        return parent::getAno();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCreacion($fechaCreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCreacion', array($fechaCreacion));

        return parent::setFechaCreacion($fechaCreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCreacion', array());

        return parent::getFechaCreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaModificacion($fechaModificacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaModificacion', array($fechaModificacion));

        return parent::setFechaModificacion($fechaModificacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaModificacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaModificacion', array());

        return parent::getFechaModificacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaRegistro($fechaRegistro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaRegistro', array($fechaRegistro));

        return parent::setFechaRegistro($fechaRegistro);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaRegistro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaRegistro', array());

        return parent::getFechaRegistro();
    }

    /**
     * {@inheritDoc}
     */
    public function setNroMatricula($nroMatricula)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNroMatricula', array($nroMatricula));

        return parent::setNroMatricula($nroMatricula);
    }

    /**
     * {@inheritDoc}
     */
    public function getNroMatricula()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNroMatricula', array());

        return parent::getNroMatricula();
    }

    /**
     * {@inheritDoc}
     */
    public function setNroProtocolo($nroProtocolo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNroProtocolo', array($nroProtocolo));

        return parent::setNroProtocolo($nroProtocolo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNroProtocolo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNroProtocolo', array());

        return parent::getNroProtocolo();
    }

    /**
     * {@inheritDoc}
     */
    public function setNroRegistro($nroRegistro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNroRegistro', array($nroRegistro));

        return parent::setNroRegistro($nroRegistro);
    }

    /**
     * {@inheritDoc}
     */
    public function getNroRegistro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNroRegistro', array());

        return parent::getNroRegistro();
    }

    /**
     * {@inheritDoc}
     */
    public function setTomo($tomo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTomo', array($tomo));

        return parent::setTomo($tomo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTomo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTomo', array());

        return parent::getTomo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnalisisCredito(\Srpv\ProtocolizacionBundle\Entity\AnalisisCredito $analisisCredito = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnalisisCredito', array($analisisCredito));

        return parent::setAnalisisCredito($analisisCredito);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnalisisCredito()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnalisisCredito', array());

        return parent::getAnalisisCredito();
    }

    /**
     * {@inheritDoc}
     */
    public function setFuenteDatosEntrada(\Srpv\ProtocolizacionBundle\Entity\FuenteDatosEntrada $fuenteDatosEntrada = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFuenteDatosEntrada', array($fuenteDatosEntrada));

        return parent::setFuenteDatosEntrada($fuenteDatosEntrada);
    }

    /**
     * {@inheritDoc}
     */
    public function getFuenteDatosEntrada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFuenteDatosEntrada', array());

        return parent::getFuenteDatosEntrada();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario(\Comunes\SecurityBundle\Entity\Usuario $usuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', array($usuario));

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', array());

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegistroPublico(\Srpv\ProtocolizacionBundle\Entity\RegistroPublico $registroPublico = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegistroPublico', array($registroPublico));

        return parent::setRegistroPublico($registroPublico);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegistroPublico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegistroPublico', array());

        return parent::getRegistroPublico();
    }

}
