<?php

namespace Proxies\__CG__\Srpv\ProtocolizacionBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Vivienda extends \Srpv\ProtocolizacionBundle\Entity\Vivienda implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'id', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'comedor', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'construccionMt2', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'coordenadas', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'descripcionEstac', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'fechaActualizacion', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'fechaCreacion', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'lavandero', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'linderoEste', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'linderoNorte', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'linderoOeste', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'linderoSur', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'nroBanos', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'nroEstacionamientos', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'nroHabitaciones', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'nroPiso', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'nroVivienda', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'precioVivienda', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'sala', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'tipoVivienda', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'fuenteDatosEntrada', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'usuario', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'unidadHabitacional');
        }

        return array('__isInitialized__', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'id', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'comedor', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'construccionMt2', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'coordenadas', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'descripcionEstac', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'fechaActualizacion', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'fechaCreacion', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'lavandero', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'linderoEste', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'linderoNorte', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'linderoOeste', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'linderoSur', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'nroBanos', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'nroEstacionamientos', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'nroHabitaciones', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'nroPiso', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'nroVivienda', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'precioVivienda', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'sala', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'tipoVivienda', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'fuenteDatosEntrada', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'usuario', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\Vivienda' . "\0" . 'unidadHabitacional');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Vivienda $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setComedor($comedor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComedor', array($comedor));

        return parent::setComedor($comedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getComedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComedor', array());

        return parent::getComedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setConstruccionMt2($construccionMt2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConstruccionMt2', array($construccionMt2));

        return parent::setConstruccionMt2($construccionMt2);
    }

    /**
     * {@inheritDoc}
     */
    public function getConstruccionMt2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConstruccionMt2', array());

        return parent::getConstruccionMt2();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoordenadas($coordenadas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoordenadas', array($coordenadas));

        return parent::setCoordenadas($coordenadas);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoordenadas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoordenadas', array());

        return parent::getCoordenadas();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcionEstac($descripcionEstac)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcionEstac', array($descripcionEstac));

        return parent::setDescripcionEstac($descripcionEstac);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcionEstac()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcionEstac', array());

        return parent::getDescripcionEstac();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaActualizacion($fechaActualizacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaActualizacion', array($fechaActualizacion));

        return parent::setFechaActualizacion($fechaActualizacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaActualizacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaActualizacion', array());

        return parent::getFechaActualizacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCreacion($fechaCreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCreacion', array($fechaCreacion));

        return parent::setFechaCreacion($fechaCreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCreacion', array());

        return parent::getFechaCreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setLavandero($lavandero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLavandero', array($lavandero));

        return parent::setLavandero($lavandero);
    }

    /**
     * {@inheritDoc}
     */
    public function getLavandero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLavandero', array());

        return parent::getLavandero();
    }

    /**
     * {@inheritDoc}
     */
    public function setLinderoEste($linderoEste)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLinderoEste', array($linderoEste));

        return parent::setLinderoEste($linderoEste);
    }

    /**
     * {@inheritDoc}
     */
    public function getLinderoEste()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLinderoEste', array());

        return parent::getLinderoEste();
    }

    /**
     * {@inheritDoc}
     */
    public function setLinderoNorte($linderoNorte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLinderoNorte', array($linderoNorte));

        return parent::setLinderoNorte($linderoNorte);
    }

    /**
     * {@inheritDoc}
     */
    public function getLinderoNorte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLinderoNorte', array());

        return parent::getLinderoNorte();
    }

    /**
     * {@inheritDoc}
     */
    public function setLinderoOeste($linderoOeste)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLinderoOeste', array($linderoOeste));

        return parent::setLinderoOeste($linderoOeste);
    }

    /**
     * {@inheritDoc}
     */
    public function getLinderoOeste()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLinderoOeste', array());

        return parent::getLinderoOeste();
    }

    /**
     * {@inheritDoc}
     */
    public function setLinderoSur($linderoSur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLinderoSur', array($linderoSur));

        return parent::setLinderoSur($linderoSur);
    }

    /**
     * {@inheritDoc}
     */
    public function getLinderoSur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLinderoSur', array());

        return parent::getLinderoSur();
    }

    /**
     * {@inheritDoc}
     */
    public function setNroBanos($nroBanos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNroBanos', array($nroBanos));

        return parent::setNroBanos($nroBanos);
    }

    /**
     * {@inheritDoc}
     */
    public function getNroBanos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNroBanos', array());

        return parent::getNroBanos();
    }

    /**
     * {@inheritDoc}
     */
    public function setNroEstacionamientos($nroEstacionamientos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNroEstacionamientos', array($nroEstacionamientos));

        return parent::setNroEstacionamientos($nroEstacionamientos);
    }

    /**
     * {@inheritDoc}
     */
    public function getNroEstacionamientos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNroEstacionamientos', array());

        return parent::getNroEstacionamientos();
    }

    /**
     * {@inheritDoc}
     */
    public function setNroHabitaciones($nroHabitaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNroHabitaciones', array($nroHabitaciones));

        return parent::setNroHabitaciones($nroHabitaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getNroHabitaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNroHabitaciones', array());

        return parent::getNroHabitaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setNroPiso($nroPiso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNroPiso', array($nroPiso));

        return parent::setNroPiso($nroPiso);
    }

    /**
     * {@inheritDoc}
     */
    public function getNroPiso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNroPiso', array());

        return parent::getNroPiso();
    }

    /**
     * {@inheritDoc}
     */
    public function setNroVivienda($nroVivienda)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNroVivienda', array($nroVivienda));

        return parent::setNroVivienda($nroVivienda);
    }

    /**
     * {@inheritDoc}
     */
    public function getNroVivienda()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNroVivienda', array());

        return parent::getNroVivienda();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecioVivienda($precioVivienda)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecioVivienda', array($precioVivienda));

        return parent::setPrecioVivienda($precioVivienda);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecioVivienda()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecioVivienda', array());

        return parent::getPrecioVivienda();
    }

    /**
     * {@inheritDoc}
     */
    public function setSala($sala)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSala', array($sala));

        return parent::setSala($sala);
    }

    /**
     * {@inheritDoc}
     */
    public function getSala()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSala', array());

        return parent::getSala();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoVivienda(\Srpv\ProtocolizacionBundle\Entity\TipoVivienda $tipoVivienda = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoVivienda', array($tipoVivienda));

        return parent::setTipoVivienda($tipoVivienda);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoVivienda()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoVivienda', array());

        return parent::getTipoVivienda();
    }

    /**
     * {@inheritDoc}
     */
    public function setFuenteDatosEntrada(\Srpv\ProtocolizacionBundle\Entity\FuenteDatosEntrada $fuenteDatosEntrada = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFuenteDatosEntrada', array($fuenteDatosEntrada));

        return parent::setFuenteDatosEntrada($fuenteDatosEntrada);
    }

    /**
     * {@inheritDoc}
     */
    public function getFuenteDatosEntrada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFuenteDatosEntrada', array());

        return parent::getFuenteDatosEntrada();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario(\Comunes\SecurityBundle\Entity\Usuario $usuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', array($usuario));

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', array());

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnidadHabitacional(\Srpv\ProtocolizacionBundle\Entity\UnidadHabitacional $unidadHabitacional = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnidadHabitacional', array($unidadHabitacional));

        return parent::setUnidadHabitacional($unidadHabitacional);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnidadHabitacional()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnidadHabitacional', array());

        return parent::getUnidadHabitacional();
    }

}
