<?php

namespace Proxies\__CG__\Srpv\ProtocolizacionBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UnidadFamiliar extends \Srpv\ProtocolizacionBundle\Entity\UnidadFamiliar implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadFamiliar' . "\0" . 'id', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadFamiliar' . "\0" . 'cantidadDispacitados', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadFamiliar' . "\0" . 'fechaActualizacion', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadFamiliar' . "\0" . 'fechaCreacion', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadFamiliar' . "\0" . 'fuenteDatosEntradaId', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadFamiliar' . "\0" . 'ingresoTotalFamiliar', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadFamiliar' . "\0" . 'nombre', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadFamiliar' . "\0" . 'totalPersonasCotizando', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadFamiliar' . "\0" . 'beneficiario', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadFamiliar' . "\0" . 'condicionUnidadFamiliar', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadFamiliar' . "\0" . 'procedenciaBeneficio', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadFamiliar' . "\0" . 'usuario');
        }

        return array('__isInitialized__', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadFamiliar' . "\0" . 'id', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadFamiliar' . "\0" . 'cantidadDispacitados', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadFamiliar' . "\0" . 'fechaActualizacion', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadFamiliar' . "\0" . 'fechaCreacion', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadFamiliar' . "\0" . 'fuenteDatosEntradaId', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadFamiliar' . "\0" . 'ingresoTotalFamiliar', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadFamiliar' . "\0" . 'nombre', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadFamiliar' . "\0" . 'totalPersonasCotizando', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadFamiliar' . "\0" . 'beneficiario', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadFamiliar' . "\0" . 'condicionUnidadFamiliar', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadFamiliar' . "\0" . 'procedenciaBeneficio', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadFamiliar' . "\0" . 'usuario');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UnidadFamiliar $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidadDispacitados($cantidadDispacitados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidadDispacitados', array($cantidadDispacitados));

        return parent::setCantidadDispacitados($cantidadDispacitados);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidadDispacitados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidadDispacitados', array());

        return parent::getCantidadDispacitados();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaActualizacion($fechaActualizacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaActualizacion', array($fechaActualizacion));

        return parent::setFechaActualizacion($fechaActualizacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaActualizacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaActualizacion', array());

        return parent::getFechaActualizacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCreacion($fechaCreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCreacion', array($fechaCreacion));

        return parent::setFechaCreacion($fechaCreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCreacion', array());

        return parent::getFechaCreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFuenteDatosEntradaId($fuenteDatosEntradaId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFuenteDatosEntradaId', array($fuenteDatosEntradaId));

        return parent::setFuenteDatosEntradaId($fuenteDatosEntradaId);
    }

    /**
     * {@inheritDoc}
     */
    public function getFuenteDatosEntradaId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFuenteDatosEntradaId', array());

        return parent::getFuenteDatosEntradaId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIngresoTotalFamiliar($ingresoTotalFamiliar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIngresoTotalFamiliar', array($ingresoTotalFamiliar));

        return parent::setIngresoTotalFamiliar($ingresoTotalFamiliar);
    }

    /**
     * {@inheritDoc}
     */
    public function getIngresoTotalFamiliar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIngresoTotalFamiliar', array());

        return parent::getIngresoTotalFamiliar();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalPersonasCotizando($totalPersonasCotizando)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalPersonasCotizando', array($totalPersonasCotizando));

        return parent::setTotalPersonasCotizando($totalPersonasCotizando);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalPersonasCotizando()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalPersonasCotizando', array());

        return parent::getTotalPersonasCotizando();
    }

    /**
     * {@inheritDoc}
     */
    public function setBeneficiario(\Srpv\ProtocolizacionBundle\Entity\Beneficiario $beneficiario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBeneficiario', array($beneficiario));

        return parent::setBeneficiario($beneficiario);
    }

    /**
     * {@inheritDoc}
     */
    public function getBeneficiario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBeneficiario', array());

        return parent::getBeneficiario();
    }

    /**
     * {@inheritDoc}
     */
    public function setCondicionUnidadFamiliar(\Srpv\ProtocolizacionBundle\Entity\CondicionUnidadFamiliar $condicionUnidadFamiliar = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCondicionUnidadFamiliar', array($condicionUnidadFamiliar));

        return parent::setCondicionUnidadFamiliar($condicionUnidadFamiliar);
    }

    /**
     * {@inheritDoc}
     */
    public function getCondicionUnidadFamiliar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCondicionUnidadFamiliar', array());

        return parent::getCondicionUnidadFamiliar();
    }

    /**
     * {@inheritDoc}
     */
    public function setProcedenciaBeneficio(\Srpv\ProtocolizacionBundle\Entity\ProcedenciaBeneficio $procedenciaBeneficio = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProcedenciaBeneficio', array($procedenciaBeneficio));

        return parent::setProcedenciaBeneficio($procedenciaBeneficio);
    }

    /**
     * {@inheritDoc}
     */
    public function getProcedenciaBeneficio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProcedenciaBeneficio', array());

        return parent::getProcedenciaBeneficio();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario(\Comunes\SecurityBundle\Entity\Usuario $usuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', array($usuario));

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', array());

        return parent::getUsuario();
    }

}
