<?php

namespace Proxies\__CG__\Srpv\ProtocolizacionBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TTipoArchivos extends \Srpv\ProtocolizacionBundle\Entity\TTipoArchivos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\TTipoArchivos' . "\0" . 'tipoArchivo', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\TTipoArchivos' . "\0" . 'cantColumnas', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\TTipoArchivos' . "\0" . 'delimitador', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\TTipoArchivos' . "\0" . 'dia', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\TTipoArchivos' . "\0" . 'entidadDesde', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\TTipoArchivos' . "\0" . 'entidadSize', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\TTipoArchivos' . "\0" . 'frecuencia', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\TTipoArchivos' . "\0" . 'frecuenciaDesde', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\TTipoArchivos' . "\0" . 'frecuenciaSize', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\TTipoArchivos' . "\0" . 'periodoDesde', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\TTipoArchivos' . "\0" . 'periodoSize', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\TTipoArchivos' . "\0" . 'poseeTipoRegs', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\TTipoArchivos' . "\0" . 'secuenciaDesde', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\TTipoArchivos' . "\0" . 'secuenciaSize', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\TTipoArchivos' . "\0" . 'tamanoNombre', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\TTipoArchivos' . "\0" . 'tamanoRegistro');
        }

        return array('__isInitialized__', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\TTipoArchivos' . "\0" . 'tipoArchivo', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\TTipoArchivos' . "\0" . 'cantColumnas', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\TTipoArchivos' . "\0" . 'delimitador', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\TTipoArchivos' . "\0" . 'dia', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\TTipoArchivos' . "\0" . 'entidadDesde', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\TTipoArchivos' . "\0" . 'entidadSize', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\TTipoArchivos' . "\0" . 'frecuencia', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\TTipoArchivos' . "\0" . 'frecuenciaDesde', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\TTipoArchivos' . "\0" . 'frecuenciaSize', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\TTipoArchivos' . "\0" . 'periodoDesde', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\TTipoArchivos' . "\0" . 'periodoSize', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\TTipoArchivos' . "\0" . 'poseeTipoRegs', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\TTipoArchivos' . "\0" . 'secuenciaDesde', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\TTipoArchivos' . "\0" . 'secuenciaSize', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\TTipoArchivos' . "\0" . 'tamanoNombre', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\TTipoArchivos' . "\0" . 'tamanoRegistro');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TTipoArchivos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getTipoArchivo()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getTipoArchivo();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoArchivo', array());

        return parent::getTipoArchivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantColumnas($cantColumnas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantColumnas', array($cantColumnas));

        return parent::setCantColumnas($cantColumnas);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantColumnas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantColumnas', array());

        return parent::getCantColumnas();
    }

    /**
     * {@inheritDoc}
     */
    public function setDelimitador($delimitador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDelimitador', array($delimitador));

        return parent::setDelimitador($delimitador);
    }

    /**
     * {@inheritDoc}
     */
    public function getDelimitador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDelimitador', array());

        return parent::getDelimitador();
    }

    /**
     * {@inheritDoc}
     */
    public function setDia($dia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDia', array($dia));

        return parent::setDia($dia);
    }

    /**
     * {@inheritDoc}
     */
    public function getDia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDia', array());

        return parent::getDia();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntidadDesde($entidadDesde)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntidadDesde', array($entidadDesde));

        return parent::setEntidadDesde($entidadDesde);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntidadDesde()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntidadDesde', array());

        return parent::getEntidadDesde();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntidadSize($entidadSize)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntidadSize', array($entidadSize));

        return parent::setEntidadSize($entidadSize);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntidadSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntidadSize', array());

        return parent::getEntidadSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setFrecuencia($frecuencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFrecuencia', array($frecuencia));

        return parent::setFrecuencia($frecuencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getFrecuencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFrecuencia', array());

        return parent::getFrecuencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setFrecuenciaDesde($frecuenciaDesde)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFrecuenciaDesde', array($frecuenciaDesde));

        return parent::setFrecuenciaDesde($frecuenciaDesde);
    }

    /**
     * {@inheritDoc}
     */
    public function getFrecuenciaDesde()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFrecuenciaDesde', array());

        return parent::getFrecuenciaDesde();
    }

    /**
     * {@inheritDoc}
     */
    public function setFrecuenciaSize($frecuenciaSize)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFrecuenciaSize', array($frecuenciaSize));

        return parent::setFrecuenciaSize($frecuenciaSize);
    }

    /**
     * {@inheritDoc}
     */
    public function getFrecuenciaSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFrecuenciaSize', array());

        return parent::getFrecuenciaSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeriodoDesde($periodoDesde)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeriodoDesde', array($periodoDesde));

        return parent::setPeriodoDesde($periodoDesde);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriodoDesde()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriodoDesde', array());

        return parent::getPeriodoDesde();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeriodoSize($periodoSize)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeriodoSize', array($periodoSize));

        return parent::setPeriodoSize($periodoSize);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriodoSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriodoSize', array());

        return parent::getPeriodoSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setPoseeTipoRegs($poseeTipoRegs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoseeTipoRegs', array($poseeTipoRegs));

        return parent::setPoseeTipoRegs($poseeTipoRegs);
    }

    /**
     * {@inheritDoc}
     */
    public function getPoseeTipoRegs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoseeTipoRegs', array());

        return parent::getPoseeTipoRegs();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecuenciaDesde($secuenciaDesde)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecuenciaDesde', array($secuenciaDesde));

        return parent::setSecuenciaDesde($secuenciaDesde);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecuenciaDesde()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecuenciaDesde', array());

        return parent::getSecuenciaDesde();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecuenciaSize($secuenciaSize)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecuenciaSize', array($secuenciaSize));

        return parent::setSecuenciaSize($secuenciaSize);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecuenciaSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecuenciaSize', array());

        return parent::getSecuenciaSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setTamanoNombre($tamanoNombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTamanoNombre', array($tamanoNombre));

        return parent::setTamanoNombre($tamanoNombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTamanoNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTamanoNombre', array());

        return parent::getTamanoNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTamanoRegistro($tamanoRegistro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTamanoRegistro', array($tamanoRegistro));

        return parent::setTamanoRegistro($tamanoRegistro);
    }

    /**
     * {@inheritDoc}
     */
    public function getTamanoRegistro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTamanoRegistro', array());

        return parent::getTamanoRegistro();
    }

}
