<?php

namespace Proxies\__CG__\Srpv\ProtocolizacionBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class BitacoraArchivo extends \Srpv\ProtocolizacionBundle\Entity\BitacoraArchivo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\BitacoraArchivo' . "\0" . 'id', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\BitacoraArchivo' . "\0" . 'codigoEstatus', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\BitacoraArchivo' . "\0" . 'codigoSqlcode', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\BitacoraArchivo' . "\0" . 'codigoSqlerrm', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\BitacoraArchivo' . "\0" . 'codigoSudeban', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\BitacoraArchivo' . "\0" . 'fechaProceso', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\BitacoraArchivo' . "\0" . 'nombreArchivo', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\BitacoraArchivo' . "\0" . 'numeroContrato', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\BitacoraArchivo' . "\0" . 'observaciones', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\BitacoraArchivo' . "\0" . 'procedimiento', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\BitacoraArchivo' . "\0" . 'tipoArchivo', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\BitacoraArchivo' . "\0" . 'idControl');
        }

        return array('__isInitialized__', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\BitacoraArchivo' . "\0" . 'id', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\BitacoraArchivo' . "\0" . 'codigoEstatus', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\BitacoraArchivo' . "\0" . 'codigoSqlcode', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\BitacoraArchivo' . "\0" . 'codigoSqlerrm', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\BitacoraArchivo' . "\0" . 'codigoSudeban', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\BitacoraArchivo' . "\0" . 'fechaProceso', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\BitacoraArchivo' . "\0" . 'nombreArchivo', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\BitacoraArchivo' . "\0" . 'numeroContrato', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\BitacoraArchivo' . "\0" . 'observaciones', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\BitacoraArchivo' . "\0" . 'procedimiento', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\BitacoraArchivo' . "\0" . 'tipoArchivo', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\BitacoraArchivo' . "\0" . 'idControl');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (BitacoraArchivo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigoEstatus($codigoEstatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigoEstatus', array($codigoEstatus));

        return parent::setCodigoEstatus($codigoEstatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigoEstatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigoEstatus', array());

        return parent::getCodigoEstatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigoSqlcode($codigoSqlcode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigoSqlcode', array($codigoSqlcode));

        return parent::setCodigoSqlcode($codigoSqlcode);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigoSqlcode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigoSqlcode', array());

        return parent::getCodigoSqlcode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigoSqlerrm($codigoSqlerrm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigoSqlerrm', array($codigoSqlerrm));

        return parent::setCodigoSqlerrm($codigoSqlerrm);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigoSqlerrm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigoSqlerrm', array());

        return parent::getCodigoSqlerrm();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigoSudeban($codigoSudeban)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigoSudeban', array($codigoSudeban));

        return parent::setCodigoSudeban($codigoSudeban);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigoSudeban()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigoSudeban', array());

        return parent::getCodigoSudeban();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaProceso($fechaProceso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaProceso', array($fechaProceso));

        return parent::setFechaProceso($fechaProceso);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaProceso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaProceso', array());

        return parent::getFechaProceso();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreArchivo($nombreArchivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreArchivo', array($nombreArchivo));

        return parent::setNombreArchivo($nombreArchivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreArchivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreArchivo', array());

        return parent::getNombreArchivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroContrato($numeroContrato)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroContrato', array($numeroContrato));

        return parent::setNumeroContrato($numeroContrato);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroContrato()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroContrato', array());

        return parent::getNumeroContrato();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservaciones($observaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservaciones', array($observaciones));

        return parent::setObservaciones($observaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservaciones', array());

        return parent::getObservaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setProcedimiento($procedimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProcedimiento', array($procedimiento));

        return parent::setProcedimiento($procedimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getProcedimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProcedimiento', array());

        return parent::getProcedimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoArchivo($tipoArchivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoArchivo', array($tipoArchivo));

        return parent::setTipoArchivo($tipoArchivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoArchivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoArchivo', array());

        return parent::getTipoArchivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdControl(\Srpv\ProtocolizacionBundle\Entity\ControlArchivos $idControl = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdControl', array($idControl));

        return parent::setIdControl($idControl);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdControl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdControl', array());

        return parent::getIdControl();
    }

}
