<?php

namespace Proxies\__CG__\Srpv\ProtocolizacionBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ControlArchivos extends \Srpv\ProtocolizacionBundle\Entity\ControlArchivos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\ControlArchivos' . "\0" . 'id', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\ControlArchivos' . "\0" . 'cantidadLineas', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\ControlArchivos' . "\0" . 'codigoEstatus', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\ControlArchivos' . "\0" . 'codigoSudeban', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\ControlArchivos' . "\0" . 'correoContacto', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\ControlArchivos' . "\0" . 'fechaCreacion', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\ControlArchivos' . "\0" . 'fechaEjecucion', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\ControlArchivos' . "\0" . 'nombreArchivo', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\ControlArchivos' . "\0" . 'observacion', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\ControlArchivos' . "\0" . 'periodo', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\ControlArchivos' . "\0" . 'tipoArchivo');
        }

        return array('__isInitialized__', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\ControlArchivos' . "\0" . 'id', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\ControlArchivos' . "\0" . 'cantidadLineas', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\ControlArchivos' . "\0" . 'codigoEstatus', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\ControlArchivos' . "\0" . 'codigoSudeban', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\ControlArchivos' . "\0" . 'correoContacto', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\ControlArchivos' . "\0" . 'fechaCreacion', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\ControlArchivos' . "\0" . 'fechaEjecucion', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\ControlArchivos' . "\0" . 'nombreArchivo', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\ControlArchivos' . "\0" . 'observacion', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\ControlArchivos' . "\0" . 'periodo', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\ControlArchivos' . "\0" . 'tipoArchivo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ControlArchivos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidadLineas($cantidadLineas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidadLineas', array($cantidadLineas));

        return parent::setCantidadLineas($cantidadLineas);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidadLineas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidadLineas', array());

        return parent::getCantidadLineas();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigoEstatus($codigoEstatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigoEstatus', array($codigoEstatus));

        return parent::setCodigoEstatus($codigoEstatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigoEstatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigoEstatus', array());

        return parent::getCodigoEstatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigoSudeban($codigoSudeban)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigoSudeban', array($codigoSudeban));

        return parent::setCodigoSudeban($codigoSudeban);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigoSudeban()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigoSudeban', array());

        return parent::getCodigoSudeban();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorreoContacto($correoContacto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorreoContacto', array($correoContacto));

        return parent::setCorreoContacto($correoContacto);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorreoContacto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorreoContacto', array());

        return parent::getCorreoContacto();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCreacion($fechaCreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCreacion', array($fechaCreacion));

        return parent::setFechaCreacion($fechaCreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCreacion', array());

        return parent::getFechaCreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaEjecucion($fechaEjecucion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaEjecucion', array($fechaEjecucion));

        return parent::setFechaEjecucion($fechaEjecucion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaEjecucion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaEjecucion', array());

        return parent::getFechaEjecucion();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreArchivo($nombreArchivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreArchivo', array($nombreArchivo));

        return parent::setNombreArchivo($nombreArchivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreArchivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreArchivo', array());

        return parent::getNombreArchivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacion($observacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacion', array($observacion));

        return parent::setObservacion($observacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacion', array());

        return parent::getObservacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeriodo($periodo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeriodo', array($periodo));

        return parent::setPeriodo($periodo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriodo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriodo', array());

        return parent::getPeriodo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoArchivo($tipoArchivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoArchivo', array($tipoArchivo));

        return parent::setTipoArchivo($tipoArchivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoArchivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoArchivo', array());

        return parent::getTipoArchivo();
    }

}
