<?php

namespace Proxies\__CG__\Srpv\ProtocolizacionBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class GrupoFamiliar extends \Srpv\ProtocolizacionBundle\Entity\GrupoFamiliar implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\GrupoFamiliar' . "\0" . 'id', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\GrupoFamiliar' . "\0" . 'fechaActualizacion', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\GrupoFamiliar' . "\0" . 'fechaCreacion', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\GrupoFamiliar' . "\0" . 'ingresoMensual', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\GrupoFamiliar' . "\0" . 'tipoSujetoAtencion', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\GrupoFamiliar' . "\0" . 'genParentesco', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\GrupoFamiliar' . "\0" . 'fuenteDatosEntrada', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\GrupoFamiliar' . "\0" . 'persona', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\GrupoFamiliar' . "\0" . 'usuario', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\GrupoFamiliar' . "\0" . 'unidadFamiliar');
        }

        return array('__isInitialized__', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\GrupoFamiliar' . "\0" . 'id', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\GrupoFamiliar' . "\0" . 'fechaActualizacion', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\GrupoFamiliar' . "\0" . 'fechaCreacion', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\GrupoFamiliar' . "\0" . 'ingresoMensual', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\GrupoFamiliar' . "\0" . 'tipoSujetoAtencion', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\GrupoFamiliar' . "\0" . 'genParentesco', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\GrupoFamiliar' . "\0" . 'fuenteDatosEntrada', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\GrupoFamiliar' . "\0" . 'persona', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\GrupoFamiliar' . "\0" . 'usuario', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\GrupoFamiliar' . "\0" . 'unidadFamiliar');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (GrupoFamiliar $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaActualizacion($fechaActualizacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaActualizacion', array($fechaActualizacion));

        return parent::setFechaActualizacion($fechaActualizacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaActualizacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaActualizacion', array());

        return parent::getFechaActualizacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCreacion($fechaCreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCreacion', array($fechaCreacion));

        return parent::setFechaCreacion($fechaCreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCreacion', array());

        return parent::getFechaCreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setIngresoMensual($ingresoMensual)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIngresoMensual', array($ingresoMensual));

        return parent::setIngresoMensual($ingresoMensual);
    }

    /**
     * {@inheritDoc}
     */
    public function getIngresoMensual()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIngresoMensual', array());

        return parent::getIngresoMensual();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoSujetoAtencion($tipoSujetoAtencion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoSujetoAtencion', array($tipoSujetoAtencion));

        return parent::setTipoSujetoAtencion($tipoSujetoAtencion);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoSujetoAtencion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoSujetoAtencion', array());

        return parent::getTipoSujetoAtencion();
    }

    /**
     * {@inheritDoc}
     */
    public function setGenParentesco(\Comunes\TablasBundle\Entity\GenParentesco $genParentesco = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGenParentesco', array($genParentesco));

        return parent::setGenParentesco($genParentesco);
    }

    /**
     * {@inheritDoc}
     */
    public function getGenParentesco()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGenParentesco', array());

        return parent::getGenParentesco();
    }

    /**
     * {@inheritDoc}
     */
    public function setFuenteDatosEntrada(\Srpv\ProtocolizacionBundle\Entity\FuenteDatosEntrada $fuenteDatosEntrada = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFuenteDatosEntrada', array($fuenteDatosEntrada));

        return parent::setFuenteDatosEntrada($fuenteDatosEntrada);
    }

    /**
     * {@inheritDoc}
     */
    public function getFuenteDatosEntrada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFuenteDatosEntrada', array());

        return parent::getFuenteDatosEntrada();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersona(\Comunes\TablasBundle\Entity\Persona $persona = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersona', array($persona));

        return parent::setPersona($persona);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersona()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersona', array());

        return parent::getPersona();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario(\Comunes\SecurityBundle\Entity\Usuario $usuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', array($usuario));

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', array());

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnidadFamiliar(\Srpv\ProtocolizacionBundle\Entity\UnidadFamiliar $unidadFamiliar = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnidadFamiliar', array($unidadFamiliar));

        return parent::setUnidadFamiliar($unidadFamiliar);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnidadFamiliar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnidadFamiliar', array());

        return parent::getUnidadFamiliar();
    }

}
