<?php

namespace Proxies\__CG__\Comunes\OrganismosPublicosBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Seniat extends \Comunes\OrganismosPublicosBundle\Entity\Seniat implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Comunes\\OrganismosPublicosBundle\\Entity\\Seniat' . "\0" . 'id', '' . "\0" . 'Comunes\\OrganismosPublicosBundle\\Entity\\Seniat' . "\0" . 'rif', '' . "\0" . 'Comunes\\OrganismosPublicosBundle\\Entity\\Seniat' . "\0" . 'nombre', '' . "\0" . 'Comunes\\OrganismosPublicosBundle\\Entity\\Seniat' . "\0" . 'direccion', '' . "\0" . 'Comunes\\OrganismosPublicosBundle\\Entity\\Seniat' . "\0" . 'actividadEconomica', '' . "\0" . 'Comunes\\OrganismosPublicosBundle\\Entity\\Seniat' . "\0" . 'telefono', '' . "\0" . 'Comunes\\OrganismosPublicosBundle\\Entity\\Seniat' . "\0" . 'correoElectronico', '' . "\0" . 'Comunes\\OrganismosPublicosBundle\\Entity\\Seniat' . "\0" . 'fechaConstitucion');
        }

        return array('__isInitialized__', '' . "\0" . 'Comunes\\OrganismosPublicosBundle\\Entity\\Seniat' . "\0" . 'id', '' . "\0" . 'Comunes\\OrganismosPublicosBundle\\Entity\\Seniat' . "\0" . 'rif', '' . "\0" . 'Comunes\\OrganismosPublicosBundle\\Entity\\Seniat' . "\0" . 'nombre', '' . "\0" . 'Comunes\\OrganismosPublicosBundle\\Entity\\Seniat' . "\0" . 'direccion', '' . "\0" . 'Comunes\\OrganismosPublicosBundle\\Entity\\Seniat' . "\0" . 'actividadEconomica', '' . "\0" . 'Comunes\\OrganismosPublicosBundle\\Entity\\Seniat' . "\0" . 'telefono', '' . "\0" . 'Comunes\\OrganismosPublicosBundle\\Entity\\Seniat' . "\0" . 'correoElectronico', '' . "\0" . 'Comunes\\OrganismosPublicosBundle\\Entity\\Seniat' . "\0" . 'fechaConstitucion');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Seniat $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRif($rif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRif', array($rif));

        return parent::setRif($rif);
    }

    /**
     * {@inheritDoc}
     */
    public function getRif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRif', array());

        return parent::getRif();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', array($direccion));

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', array());

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setActividadEconomica($actividadEconomica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActividadEconomica', array($actividadEconomica));

        return parent::setActividadEconomica($actividadEconomica);
    }

    /**
     * {@inheritDoc}
     */
    public function getActividadEconomica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActividadEconomica', array());

        return parent::getActividadEconomica();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', array($telefono));

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', array());

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorreoElectronico($correoElectronico)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorreoElectronico', array($correoElectronico));

        return parent::setCorreoElectronico($correoElectronico);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorreoElectronico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorreoElectronico', array());

        return parent::getCorreoElectronico();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaConstitucion($fechaConstitucion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaConstitucion', array($fechaConstitucion));

        return parent::setFechaConstitucion($fechaConstitucion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaConstitucion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaConstitucion', array());

        return parent::getFechaConstitucion();
    }

}
