<?php

namespace Proxies\__CG__\Srpv\ProtocolizacionBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UnidadHabitacional extends \Srpv\ProtocolizacionBundle\Entity\UnidadHabitacional implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'id', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'ano', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'asientoRegistral', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'fechaActualizacion', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'fechaCreacion', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'fechaRegistro', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'folioReal', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'nombre', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'nroDocumento', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'nroMatricula', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'nroProtocolo', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'registroPublicoId', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'tomo', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'totalUnidades', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'fuenteDatosEntrada', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'desarrollo', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'estatusUnidadHabitacional', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'genTipoInmueble', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'tipoDocumento', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'usuario');
        }

        return array('__isInitialized__', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'id', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'ano', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'asientoRegistral', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'fechaActualizacion', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'fechaCreacion', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'fechaRegistro', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'folioReal', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'nombre', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'nroDocumento', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'nroMatricula', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'nroProtocolo', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'registroPublicoId', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'tomo', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'totalUnidades', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'fuenteDatosEntrada', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'desarrollo', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'estatusUnidadHabitacional', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'genTipoInmueble', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'tipoDocumento', '' . "\0" . 'Srpv\\ProtocolizacionBundle\\Entity\\UnidadHabitacional' . "\0" . 'usuario');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UnidadHabitacional $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAno($ano)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAno', array($ano));

        return parent::setAno($ano);
    }

    /**
     * {@inheritDoc}
     */
    public function getAno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAno', array());

        return parent::getAno();
    }

    /**
     * {@inheritDoc}
     */
    public function setAsientoRegistral($asientoRegistral)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAsientoRegistral', array($asientoRegistral));

        return parent::setAsientoRegistral($asientoRegistral);
    }

    /**
     * {@inheritDoc}
     */
    public function getAsientoRegistral()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAsientoRegistral', array());

        return parent::getAsientoRegistral();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaActualizacion($fechaActualizacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaActualizacion', array($fechaActualizacion));

        return parent::setFechaActualizacion($fechaActualizacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaActualizacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaActualizacion', array());

        return parent::getFechaActualizacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCreacion($fechaCreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCreacion', array($fechaCreacion));

        return parent::setFechaCreacion($fechaCreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCreacion', array());

        return parent::getFechaCreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaRegistro($fechaRegistro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaRegistro', array($fechaRegistro));

        return parent::setFechaRegistro($fechaRegistro);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaRegistro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaRegistro', array());

        return parent::getFechaRegistro();
    }

    /**
     * {@inheritDoc}
     */
    public function setFolioReal($folioReal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFolioReal', array($folioReal));

        return parent::setFolioReal($folioReal);
    }

    /**
     * {@inheritDoc}
     */
    public function getFolioReal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFolioReal', array());

        return parent::getFolioReal();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNroDocumento($nroDocumento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNroDocumento', array($nroDocumento));

        return parent::setNroDocumento($nroDocumento);
    }

    /**
     * {@inheritDoc}
     */
    public function getNroDocumento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNroDocumento', array());

        return parent::getNroDocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function setNroMatricula($nroMatricula)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNroMatricula', array($nroMatricula));

        return parent::setNroMatricula($nroMatricula);
    }

    /**
     * {@inheritDoc}
     */
    public function getNroMatricula()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNroMatricula', array());

        return parent::getNroMatricula();
    }

    /**
     * {@inheritDoc}
     */
    public function setNroProtocolo($nroProtocolo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNroProtocolo', array($nroProtocolo));

        return parent::setNroProtocolo($nroProtocolo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNroProtocolo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNroProtocolo', array());

        return parent::getNroProtocolo();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegistroPublicoId($registroPublicoId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegistroPublicoId', array($registroPublicoId));

        return parent::setRegistroPublicoId($registroPublicoId);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegistroPublicoId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegistroPublicoId', array());

        return parent::getRegistroPublicoId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTomo($tomo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTomo', array($tomo));

        return parent::setTomo($tomo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTomo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTomo', array());

        return parent::getTomo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalUnidades($totalUnidades)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalUnidades', array($totalUnidades));

        return parent::setTotalUnidades($totalUnidades);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalUnidades()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalUnidades', array());

        return parent::getTotalUnidades();
    }

    /**
     * {@inheritDoc}
     */
    public function setFuenteDatosEntrada(\Srpv\ProtocolizacionBundle\Entity\FuenteDatosEntrada $fuenteDatosEntrada = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFuenteDatosEntrada', array($fuenteDatosEntrada));

        return parent::setFuenteDatosEntrada($fuenteDatosEntrada);
    }

    /**
     * {@inheritDoc}
     */
    public function getFuenteDatosEntrada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFuenteDatosEntrada', array());

        return parent::getFuenteDatosEntrada();
    }

    /**
     * {@inheritDoc}
     */
    public function setDesarrollo(\Srpv\ProtocolizacionBundle\Entity\Desarrollo $desarrollo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDesarrollo', array($desarrollo));

        return parent::setDesarrollo($desarrollo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDesarrollo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDesarrollo', array());

        return parent::getDesarrollo();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstatusUnidadHabitacional(\Srpv\ProtocolizacionBundle\Entity\EstatusUnidadHabitacional $estatusUnidadHabitacional = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstatusUnidadHabitacional', array($estatusUnidadHabitacional));

        return parent::setEstatusUnidadHabitacional($estatusUnidadHabitacional);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstatusUnidadHabitacional()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstatusUnidadHabitacional', array());

        return parent::getEstatusUnidadHabitacional();
    }

    /**
     * {@inheritDoc}
     */
    public function setGenTipoInmueble(\Comunes\TablasBundle\Entity\GenTipoInmueble $genTipoInmueble = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGenTipoInmueble', array($genTipoInmueble));

        return parent::setGenTipoInmueble($genTipoInmueble);
    }

    /**
     * {@inheritDoc}
     */
    public function getGenTipoInmueble()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGenTipoInmueble', array());

        return parent::getGenTipoInmueble();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoDocumento(\Srpv\ProtocolizacionBundle\Entity\TipoDocumento $tipoDocumento = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoDocumento', array($tipoDocumento));

        return parent::setTipoDocumento($tipoDocumento);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoDocumento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoDocumento', array());

        return parent::getTipoDocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario(\Comunes\SecurityBundle\Entity\Usuario $usuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', array($usuario));

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', array());

        return parent::getUsuario();
    }

}
