<?php

namespace Srpv\ProtocolizacionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UnidadHabitacionalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnidadHabitacionalRepository extends EntityRepository
{
    public function getUnidades()
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT u.id AS id, d.nombre AS desarrollo, u.nombre AS unidad, e.nombre AS estado  FROM  SrpvProtocolizacionBundle:Desarrollo d, SrpvProtocolizacionBundle:UnidadHabitacional u, ComunesTablasBundle:GeoEstado e WHERE d.geoEstado = e.id AND u.desarrollo = d.id"
            )
            ->getResult();
    }
    
    public function getUnidadPorEstadoYDesarrollo($estadoid,$desarrolloid)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT u.id AS id, d.nombre AS desarrollo, u.nombre AS unidad, e.nombre AS estado FROM  SrpvProtocolizacionBundle:Desarrollo d, SrpvProtocolizacionBundle:UnidadHabitacional u, ComunesTablasBundle:GeoEstado e WHERE d.geoEstado = '$estadoid' AND d.geoEstado = e.id AND d.id = '$desarrolloid' AND u.desarrollo = d.id"
            )
            ->getResult();
    }
    
    public function getUnidadPorEstado($estadoid)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT u.id AS id, d.nombre AS desarrollo, u.nombre AS unidad, e.nombre AS estado FROM  SrpvProtocolizacionBundle:Desarrollo d, SrpvProtocolizacionBundle:UnidadHabitacional u, ComunesTablasBundle:GeoEstado e WHERE d.geoEstado = '$estadoid' AND d.geoEstado = e.id AND u.desarrollo = d.id"
            )
            ->getResult();
    }
    
    public function getUnidadPorDesarrollo($desarrolloid)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT u.id AS id, d.nombre AS desarrollo, u.nombre AS unidad, e.nombre AS estado FROM  SrpvProtocolizacionBundle:Desarrollo d, SrpvProtocolizacionBundle:UnidadHabitacional u, ComunesTablasBundle:GeoEstado e WHERE d.geoEstado = e.id AND d.id = '$desarrolloid' AND u.desarrollo = d.id"
            )
            ->getResult();
    }
}