<?php

namespace Srpv\ProtocolizacionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UnidadHabitacionalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnidadHabitacionalRepository extends EntityRepository
{
    public function getUnidadPorEstadoYDesarrollo($estadoid,$desarrolloid)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT u FROM  SrpvProtocolizacionBundle:Desarrollo d, SrpvProtocolizacionBundle:UnidadHabitacional u WHERE d.geoEstado = '$estadoid' AND d.id = '$desarrolloid' AND u.desarrollo = d.id"
            )
            ->getResult();
    }
    
    public function getUnidadPorEstado($estadoid)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT u FROM  SrpvProtocolizacionBundle:Desarrollo d, SrpvProtocolizacionBundle:UnidadHabitacional u WHERE d.geoEstado = '$estadoid' AND u.desarrollo = d.id"
            )
            ->getResult();
    }
}