<?php

namespace Srpv\ProtocolizacionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ViviendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViviendaRepository extends EntityRepository
{
    public function getViviendas()
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT t.nombre AS vivienda, d.nombre AS desarrollo, u.nombre AS unidad, e.nombre AS estado FROM  SrpvProtocolizacionBundle:Desarrollo d, SrpvProtocolizacionBundle:UnidadHabitacional u, SrpvProtocolizacionBundle:Vivienda v, ComunesTablasBundle:GeoEstado e, SrpvProtocolizacionBundle:TipoVivienda t WHERE d.geoEstado = e.id AND t.id = v.tipoVivienda AND u.desarrollo = d.id AND v.unidadHabitacional = u.id"
            )
            ->getResult();
    }
    
    public function getViviendaPorEstadoDesarrolloUnidad($estadoid,$desarrolloid,$unidadid)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT t.nombre AS vivienda, d.nombre AS desarrollo, u.nombre AS unidad, e.nombre AS estado FROM  SrpvProtocolizacionBundle:Desarrollo d, SrpvProtocolizacionBundle:UnidadHabitacional u, SrpvProtocolizacionBundle:Vivienda v, ComunesTablasBundle:GeoEstado e, SrpvProtocolizacionBundle:TipoVivienda t WHERE d.geoEstado = '$estadoid' AND d.geoEstado = e.id AND t.id = v.tipoVivienda AND d.id = '$desarrolloid' AND u.desarrollo = d.id AND u.id = '$unidadid' AND v.unidadHabitacional = u.id"
            )
            ->getResult();
    }
    
    public function getViviendaPorEstadoDesarrollo($estadoid,$desarrolloid)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT t.nombre AS vivienda, d.nombre AS desarrollo, u.nombre AS unidad, e.nombre AS estado FROM  SrpvProtocolizacionBundle:Desarrollo d, SrpvProtocolizacionBundle:UnidadHabitacional u, SrpvProtocolizacionBundle:Vivienda v, ComunesTablasBundle:GeoEstado e, SrpvProtocolizacionBundle:TipoVivienda t WHERE d.geoEstado = '$estadoid' AND d.geoEstado = e.id AND t.id = v.tipoVivienda AND d.id = '$desarrolloid' AND u.desarrollo = d.id AND v.unidadHabitacional = u.id"
            )
            ->getResult();
    }
    
    public function getViviendaPorEstadoUnidad($estadoid,$unidadid)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT t.nombre AS vivienda, d.nombre AS desarrollo, u.nombre AS unidad, e.nombre AS estado FROM  SrpvProtocolizacionBundle:Desarrollo d, SrpvProtocolizacionBundle:UnidadHabitacional u, SrpvProtocolizacionBundle:Vivienda v, ComunesTablasBundle:GeoEstado e, SrpvProtocolizacionBundle:TipoVivienda t WHERE d.geoEstado = '$estadoid' AND d.geoEstado = e.id AND t.id = v.tipoVivienda AND u.desarrollo = d.id AND u.id = '$unidadid' AND v.unidadHabitacional = u.id"
            )
            ->getResult();
    }
    
    public function getViviendaPorDesarrolloUnidad($desarrolloid,$unidadid)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT t.nombre AS vivienda, d.nombre AS desarrollo, u.nombre AS unidad, e.nombre AS estado FROM  SrpvProtocolizacionBundle:Desarrollo d, SrpvProtocolizacionBundle:UnidadHabitacional u, SrpvProtocolizacionBundle:Vivienda v, ComunesTablasBundle:GeoEstado e, SrpvProtocolizacionBundle:TipoVivienda t WHERE d.id = '$desarrolloid' AND d.geoEstado = e.id AND t.id = v.tipoVivienda AND u.desarrollo = d.id AND u.id = '$unidadid' AND v.unidadHabitacional = u.id"
            )
            ->getResult();
    }
    
    public function getViviendaPorEstado($estadoid)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT t.nombre AS vivienda, d.nombre AS desarrollo, u.nombre AS unidad, e.nombre AS estado FROM  SrpvProtocolizacionBundle:Desarrollo d, SrpvProtocolizacionBundle:UnidadHabitacional u, SrpvProtocolizacionBundle:Vivienda v, ComunesTablasBundle:GeoEstado e, SrpvProtocolizacionBundle:TipoVivienda t WHERE d.geoEstado = '$estadoid' AND d.geoEstado = e.id AND t.id = v.tipoVivienda AND u.desarrollo = d.id AND v.unidadHabitacional = u.id"
            )
            ->getResult();
    }
    
    public function getViviendaPorDesarrollo($desarrolloid)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT t.nombre AS vivienda, d.nombre AS desarrollo, u.nombre AS unidad, e.nombre AS estado FROM  SrpvProtocolizacionBundle:Desarrollo d, SrpvProtocolizacionBundle:UnidadHabitacional u, SrpvProtocolizacionBundle:Vivienda v, ComunesTablasBundle:GeoEstado e, SrpvProtocolizacionBundle:TipoVivienda t WHERE d.id = '$desarrolloid' AND d.geoEstado = e.id AND t.id = v.tipoVivienda AND u.desarrollo = d.id AND v.unidadHabitacional = u.id"
            )
            ->getResult();
    }
    
    public function getViviendaPorUnidad($unidadid)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT t.nombre AS vivienda, d.nombre AS desarrollo, u.nombre AS unidad, e.nombre AS estado FROM  SrpvProtocolizacionBundle:Desarrollo d, SrpvProtocolizacionBundle:UnidadHabitacional u, SrpvProtocolizacionBundle:Vivienda v, ComunesTablasBundle:GeoEstado e, SrpvProtocolizacionBundle:TipoVivienda t WHERE d.geoEstado = e.id AND t.id = v.tipoVivienda AND u.desarrollo = d.id AND u.id = '$unidadid' AND v.unidadHabitacional = u.id"
            )
            ->getResult();
    }
}