Srpv\ProtocolizacionBundle\Entity\Abogados:
    type: entity
    table: ABOGADOS
    indexes:
        IDX_96E40C6AB9546268:
            columns:
                - OFICINA_ID
        IDX_96E40C6AE8EA1841:
            columns:
                - USUARIO_ID
        IDX_96E40C6AC62AD666:
            columns:
                - PERSONA_ID
        IDX_96E40C6AF10517DF:
            columns:
                - TIPO_ABOGADO_ID
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id
            generator:
                strategy: SEQUENCE
    fields:
        estatus:
            type: string
            nullable: true
            length: 1
            fixed: true
            comment: ''
            column: ESTATUS
        fechaActualizacion:
            type: date
            nullable: true
            comment: ''
            column: FECHA_ACTUALIZACION
        fechaCreacion:
            type: date
            nullable: true
            comment: ''
            column: FECHA_CREACION
        inpreabogado:
            type: string
            nullable: true
            length: 20
            fixed: false
            comment: ''
            column: INPREABOGADO
        observaciones:
            type: string
            nullable: true
            length: 200
            fixed: false
            comment: ''
            column: OBSERVACIONES
    manyToOne:
        oficina:
            targetEntity: Oficina
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                OFICINA_ID:
                    referencedColumnName: id
            orphanRemoval: false
        usuario:
            targetEntity: Comunes\SecurityBundle\Entity\Usuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                USUARIO_ID:
                    referencedColumnName: id
            orphanRemoval: false
        persona:
            targetEntity: Comunes\TablasBundle\Entity\Persona
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                PERSONA_ID:
                    referencedColumnName: id
            orphanRemoval: false
        tipoAbogado:
            targetEntity: TipoAbogado
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                TIPO_ABOGADO_ID:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
