Srpv\ProtocolizacionBundle\Entity\EstatusUnidadHabitacional:
    type: entity
    table: ESTATUS_UNIDAD_HABITACIONAL
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id
            generator:
                strategy: SEQUENCE
    fields:
        descripcion:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: DESCRIPCION
        estatus:
            type: string
            nullable: false
            length: 1
            fixed: true
            comment: ''
            column: ESTATUS
        fechaActualizacion:
            type: date
            nullable: true
            comment: ''
            column: FECHA_ACTUALIZACION
        fechaCreacion:
            type: date
            nullable: false
            comment: ''
            column: FECHA_CREACION
        nombre:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: NOMBRE
    lifecycleCallbacks: {  }
