Srpv\ProtocolizacionBundle\Entity\EstatusBeneficiario:
    type: entity
    table: ESTATUS_BENEFICIARIO
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id
            generator:
                strategy: SEQUENCE
    fields:
        descripcion:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: DESCRIPCION
        nombre:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: NOMBRE
    lifecycleCallbacks: {  }
