Srpv\ProtocolizacionBundle\Entity\Oficina:
    type: entity
    table: OFICINA
    indexes:
        IDX_3A065BB66F3929D7:
            columns:
                - GEO_ESTADO_ID
        IDX_3A065BB67181F310:
            columns:
                - GEO_MUNICIPIO_ID
        IDX_3A065BB65D9234E7:
            columns:
                - GEO_PARROQUIA_ID
        IDX_3A065BB6E8EA1841:
            columns:
                - USUARIO_ID
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id
            generator:
                strategy: SEQUENCE
    fields:
        estatus:
            type: string
            nullable: false
            length: 1
            fixed: true
            comment: ''
            column: ESTATUS
        fechaActualizacion:
            type: date
            nullable: true
            comment: ''
            column: FECHA_ACTUALIZACION
        fechaCreacion:
            type: date
            nullable: false
            comment: ''
            column: FECHA_CREACION
        nombre:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
            column: NOMBRE
        observaciones:
            type: string
            nullable: true
            length: 200
            fixed: false
            comment: ''
            column: OBSERVACIONES
        personaIdJefe:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: PERSONA_ID_JEFE
    manyToOne:
        geoEstado:
            targetEntity: Comunes\TablasBundle\Entity\GeoEstado
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                GEO_ESTADO_ID:
                    referencedColumnName: id
            orphanRemoval: false
        geoMunicipio:
            targetEntity: Comunes\TablasBundle\Entity\GeoMunicipio
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                GEO_MUNICIPIO_ID:
                    referencedColumnName: id
            orphanRemoval: false
        geoParroquia:
            targetEntity: Comunes\TablasBundle\Entity\GeoParroquia
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                GEO_PARROQUIA_ID:
                    referencedColumnName: id
            orphanRemoval: false
        usuario:
            targetEntity: Comunes\SecurityBundle\Entity\Usuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                USUARIO_ID:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
