Srpv\ProtocolizacionBundle\Entity\ProcedenciaBeneficio:
    type: entity
    table: PROCEDENCIA_BENEFICIO
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id
            generator:
                strategy: SEQUENCE
    fields:
        fechaCreacion:
            type: date
            nullable: false
            comment: ''
            column: FECHA_CREACION
        fechaModificacion:
            type: date
            nullable: true
            comment: ''
            column: FECHA_MODIFICACION
        nombre:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: NOMBRE
    lifecycleCallbacks: {  }
