Srpv\ProtocolizacionBundle\Entity\TasaFongar:
    type: entity
    table: TASA_FONGAR
    indexes:
        IDX_C8568974E8EA1841:
            columns:
                - USUARIO_ID
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id
            generator:
                strategy: SEQUENCE
    fields:
        estatus:
            type: string
            nullable: true
            length: 1
            fixed: true
            comment: ''
            column: ESTATUS
        fechaActualizacion:
            type: date
            nullable: true
            comment: ''
            column: FECHA_ACTUALIZACION
        fechaCreacion:
            type: date
            nullable: true
            comment: ''
            column: FECHA_CREACION
        observaciones:
            type: string
            nullable: true
            length: 200
            fixed: false
            comment: ''
            column: OBSERVACIONES
        porcentajeInicial:
            type: decimal
            nullable: true
            precision: 3
            scale: 2
            comment: ''
            column: PORCENTAJE_INICIAL
        porcentajeRenovacion:
            type: decimal
            nullable: true
            precision: 5
            scale: 2
            comment: ''
            column: PORCENTAJE_RENOVACION
    manyToOne:
        usuario:
            targetEntity: Comunes\SecurityBundle\Entity\Usuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
            
            
    lifecycleCallbacks: {  }
