Srpv\ProtocolizacionBundle\Entity\TipoSubsidio:
    type: entity
    table: TIPO_SUBSIDIO
    indexes:
        IDX_10592F05E8EA1841:
            columns:
                - USUARIO_ID
        IDX_10592F0567A51867:
            columns:
                - GACETAS_PTOS_CTA_ID
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id
            generator:
                strategy: SEQUENCE
    fields:
        descripcion:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: DESCRIPCION
        estatus:
            type: string
            nullable: false
            length: 1
            fixed: true
            comment: ''
            column: ESTATUS
        fechaActualizacion:
            type: date
            nullable: true
            comment: ''
            column: FECHA_ACTUALIZACION
        fechaCreacion:
            type: date
            nullable: false
            comment: ''
            column: FECHA_CREACION
        nombre:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: NOMBRE
    manyToOne:
        usuario:
            targetEntity: Comunes\SecurityBundle\Entity\Usuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                USUARIO_ID:
                    referencedColumnName: id
            orphanRemoval: false
        gacetasPtosCta:
            targetEntity: GacetasPuntosCta
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                GACETAS_PTOS_CTA_ID:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
