Srpv\ProtocolizacionBundle\Entity\TipoDocumento:
    type: entity
    table: TIPO_DOCUMENTO
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id
            generator:
                strategy: SEQUENCE
    fields:
        estatus:
            type: string
            nullable: true
            length: 1
            fixed: true
            comment: ''
            column: ESTATUS
        fechaActualizacion:
            type: date
            nullable: true
            comment: ''
            column: FECHA_ACTUALIZACION
        fechaCreacion:
            type: date
            nullable: true
            comment: ''
            column: FECHA_CREACION
        nombre:
            type: string
            nullable: true
            length: 200
            fixed: false
            comment: ''
            column: NOMBRE
        observaciones:
            type: string
            nullable: true
            length: 200
            fixed: false
            comment: ''
            column: OBSERVACIONES
    lifecycleCallbacks: {  }
